### ISSUE TITLE
Challonge bracket didn't update automatically after a clanwar

### ISSUE THREAD

**Issue by Paul-Michaud** [ScalaWilliam/ActionFPS#376]
bracket : http://challonge.com/fr/actionfps_4
clanwar : https://actionfps.com/clanwar/?id=2017-05-12T09:56:54Z

The tournament was started, WoopDrakas had admin access.

**Comment by ScalaWilliam** [comment]
Thanks for this. I think I fixed it above ^.

**Comment by Paul-Michaud** [comment]
Still not, It should have registered that game : https://actionfps.com/clanwar/?id=2017-05-15T17:35:38Z

**Comment by ScalaWilliam** [comment]
#387, #421.
